# Generated by Django 6.0.2 on 2026-02-04 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('role', models.CharField(choices=[('Batsman', 'Batsman'), ('Bowler', 'Bowler'), ('All-Rounder', 'All-Rounder'), ('Wicket-Keeper', 'Wicket-Keeper')], max_length=30)),
                ('base_price', models.IntegerField(default=500)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='players/')),
                ('is_sold', models.BooleanField(default=False)),
                ('sold_price', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
