# Generated by Django 6.0.2 on 2026-02-04 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='agreed_terms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='players/docs/'),
        ),
        migrations.AddField(
            model_name='player',
            name='experience',
            field=models.CharField(blank=True, choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Professional', 'Professional')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='mobile',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='player_id',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='player',
            name='playing_style',
            field=models.CharField(blank=True, choices=[('Right-Hand', 'Right-Hand'), ('Left-Hand', 'Left-Hand'), ('Fast Bowler', 'Fast Bowler'), ('Spin Bowler', 'Spin Bowler')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='players/photos/'),
        ),
        migrations.AlterField(
            model_name='player',
            name='role',
            field=models.CharField(blank=True, choices=[('Batsman', 'Batsman'), ('Bowler', 'Bowler'), ('All-Rounder', 'All-Rounder'), ('Wicket-Keeper', 'Wicket-Keeper')], max_length=30, null=True),
        ),
    ]
