# Generated by Django 6.0.2 on 2026-02-05 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_alter_auction_id_alter_player_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('owner', models.CharField(blank=True, max_length=100, null=True)),
                ('total_budget', models.IntegerField(default=50000)),
                ('remaining_budget', models.IntegerField(default=50000)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='teams/logo/')),
            ],
        ),
    ]
