# Generated by Django 6.0.2 on 2026-03-03 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0006_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='payment_amount',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='player',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
    ]
