# Generated by Django 6.0.2 on 2026-03-03 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0007_player_payment_amount_player_payment_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auction_enabled', models.BooleanField(default=False)),
                ('auction_start_time', models.DateTimeField(blank=True, null=True)),
                ('maintenance_mode', models.BooleanField(default=False)),
            ],
        ),
    ]
