# Generated by Django 6.0.2 on 2026-03-05 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0008_sitesetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
