# Generated by Django 6.0.2 on 2026-03-10 04:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0010_player_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='player',
            name='payment_amount',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='player',
            name='player_id',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
