# Generated by Django 6.0.2 on 2026-04-02 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0012_alter_player_document_alter_player_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='players/docs/'),
        ),
        migrations.AlterField(
            model_name='player',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='players/photos/'),
        ),
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='teams/logo/'),
        ),
    ]
