# Generated by Django 6.0.2 on 2026-04-03 05:39

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0013_alter_player_document_alter_player_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='document',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='raw'),
        ),
        migrations.AlterField(
            model_name='player',
            name='photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
