# Generated by Django 6.0.2 on 2026-04-03 06:23

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0014_alter_player_document_alter_player_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
